apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespaces.backend }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@db:5432/%s" .Values.db.credentials.user .Values.db.credentials.password .Values.db.credentials.database | quote }}
  TMDB_API_KEY: {{ .Values.backend.tmdbApiKey | quote }}
