apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespaces.backend }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ printf "%s:%s" .Values.backend.image.repository .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: backend-secrets
