apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespaces.db }}
spec:
  serviceName: db                 # must match the headless Service name
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.db.storage.className }}
        resources:
          requests:
            storage: {{ .Values.db.storage.size | quote }}
