apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespaces.db }}
spec:
  clusterIP: None        # headless — returns db-0's address directly
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
